language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.6.6
      env: FARADAY_VERSION=0.9.0
    - rvm: 2.6.6
      env: FARADAY_VERSION=0.17.0
    - rvm: 2.6.6
      env: FARADAY_VERSION="~> 1.0"
    - rvm: 2.6.6
      script:
        - bundle exec danger
    - rvm: 2.3.8
    - rvm: jruby-9.2.7.0
    - rvm: jruby-head
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

bundler_args: --without development
