language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.3.1
      script:
        - bundle exec danger
    - rvm: 2.3.1
    - rvm: 2.3.0
    - rvm: 2.2.5
    - rvm: 2.4.0
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.1.7.0
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

before_install:
  - gem update --system
  - gem install bundler

bundler_args: --without development
