language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.6.3
    - rvm: 2.5.5
    - rvm: 2.4.6
    - rvm: 2.4.6
      script:
        - bundle exec danger
    - rvm: jruby-9.1.12.0
    - rvm: jruby-head
    - rvm: 2.3.8
    - rvm: rbx-2
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

before_install:
  - gem update --system
  - gem install bundler

bundler_args: --without development
